name: Go Testing only changed files.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get changed files
        id: files
        run: |
          FILES=$(git --no-pager diff --name-only origin/main ${{ github.event.pull_request.head.sha }} | grep '_test.go$' | sed 's/.go$/_test.go/' | paste -sd " ")
          echo "::set-env name=FILES::$FILES"

      - name: Run tests
        run: |
          go test -v -race -coverprofile=coverage.out $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
