name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get changed files
        id: files
        run: echo "::set-output name=files::$(git --no-pager diff --name-only origin/main ${{ github.event.pull_request.head.sha }})"

      - name: Run tests
        run: |
          go test -v -race -coverprofile=coverage.out $(cat ${{ steps.files.outputs.files }} | grep '_test.go$' | sed 's/.go$/_test.go/' | paste -sd " ")
